server:
  port: 8080

spring:
  application:
    name: proxy



  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              # Or√≠genes frontend eliminados
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

      routes:
        # Swagger usuario
        - id: usuario-swagger
          uri: http://localhost:8081
          predicates:
            - Path=/usuario/doc/**, /usuario/v3/api-docs/**
          filters:
            - StripPrefix=1

        # Swagger producto
        - id: producto-swagger
          uri: http://localhost:8082
          predicates:
            - Path=/producto/doc/**, /producto/v3/api-docs/**
          filters:
            - StripPrefix=1

        # Solo rutas de producto y usuario
        - id: usuarios
          uri: http://localhost:8082
          predicates:
            - Path=/usuarios/**

        - id: productos
          uri: http://localhost:8081
          predicates:
            - Path=/productos/**



